### ISSUE TITLE
Init error: order or arguments

### ISSUE THREAD

**Issue by jonathanwkelly** [phone2action/ym-api#4]
If I `new \P2A\YourMembership\YourMembershipClient($publicKey, $saPassword)` as the README says, I get an error. Can you move the injected Guzzle client to be the last argument in the `YourMembershipClient` constructor? (I think the order or params/injections is inconsequential when Reflector is in play, which isn't the case in the calling context.)

```FatalThrowableError in YourMembershipClient.php line 23:   Type error: Argument 1 passed to P2A\YourMembership\YourMembershipClient::__construct() must be an instance of GuzzleHttp\Client, string given```

**Comment by Ikstar** [comment]
Addressed in #5
